In [2]:
import numpy as np

arr = np.arange(25)

print(arr)

new_arr = arr.reshape(5,5)

print(new_arr)

print(new_arr.shape)

print(new_arr.max())

print(new_arr.argmax())

print(new_arr.min())

print(new_arr.argmin())

print(new_arr.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
(5, 5)
24
24
0
0
int64


In [5]:
import numpy as np

arr= np.arange(1,11)

In [6]:
arr[3]

np.int64(4)

In [8]:
arr.dtype

dtype('int64')

In [12]:
arr[2:6]

array([3, 4, 5, 6])

In [13]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [14]:
arr[arr<2]=20

In [15]:
arr

array([20,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr.reshape(2,5)

array([[20,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
arr.max()

np.int64(20)

In [19]:
arr.min()

np.int64(2)

In [20]:
arr.argmin()

np.int64(1)

In [21]:
print(arr.max())

20


In [22]:
print(arr.min())

2


In [23]:
print(arr.argmin())

1


In [24]:
print(arr.argmax())

0


In [26]:
print(arr[[1,5,8]])

[2 6 9]


In [ ]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([35,40,45,50,55,60])
m,c=np.polyfit(x,y,1)
print("Slope:",m)
print("Intercept:",c)



In [ ]:
import numpy as np

x = np.array(list(map(float, input("Enter number of rooms: ").split())))
y = np.array(list(map(float, input("Enter prices: ").split())))

m, c = np.polyfit(x, y, 1)

print("Slope:", m)
print("Intercept:", c)

# Prediction
rooms = float(input("Enter rooms to predict price: "))
predicted_price = m * rooms + c

print("Predicted Price:", predicted_price)